### ISSUE TITLE
Statische Html Seite auf dem Backend einrichten 

### ISSUE THREAD

**Issue by JorisJH** [AppFridaysForFutureDE/backend#100]
Es soll eine Statische Html Seite auf dem Backendgeben die via Webview in die App einbezogen wird. Wichtig wäre, dass die Seite auch über https erreichbar ist. 
Der Inhalt ist erstmal nicht so relevant 
Und die Url eigentlich auch nicht. Vlt sowas wie strike-site oder so

**Comment by NikolaiKircher** [comment]
zum test: https://app.fffutu.re/strike-site.html

**Comment by ferb300** [comment]
Issue wurde ins static repo "verschoben"
