### ISSUE TITLE
"Statische" json Antwort vom server 

### ISSUE THREAD

**Issue by JorisJH** [AppFridaysForFutureDE/backend#101]
Wir brauchen eine statische Json Antwort vom server auf einen request der ein json mit den Folgenen Felder zurückgibt: 
isAction:Bolean 
actionText:String
actionUrl:String 
das wäre super

**Comment by ferb300** [comment]
Wofür?

**Comment by NikolaiKircher** [comment]
für eine art liveticker/ newsfeed als banner in der app.
@JorisJH Was meinst du mit statisch? Wie und wie oft soll der Text geändert werden können?

**Comment by JorisJH** [comment]
<img width="340" alt="Bildschirmfoto 2020-05-21 um 12 51 26" src="https://user-images.githubusercontent.com/15171005/82569971-3fb2f280-9b81-11ea-88f7-6ef674fea18f.png">
Es soll immer wenn ein Event live ist so ein Banner in der App erscheinen

**Comment by JorisJH** [comment]
Und mit Statisch meine ich das ich da erst mal nicht viel aufwand reinstecken müsst, sondern es reicht wenn das erstmal relativ einfach auf dem backend hinterlegt ist. Theoretisch müsste aber immer wenn der Livestream online und offline geht das false zu true und umgekehrt gewechselt werden. Also nächste Woche zweimal pro tag. Wenn ihr mir ssh zugriff oder so gebt kann ich das aber sonst immer manuell machen

**Comment by NikolaiKircher** [comment]
@ferb300  was hälst du davon, dass wir das in die mongo db schreiben und ein formular in das admin panel auf unserer webseite einbauen? https://app.fffutu.re/controls/

Alternative wäre, die json Datei auf den Server zu legen und diese bei einer http anfrage direkt auszulesen.

**Comment by ferb300** [comment]
@NikolaiKircher 1a Idee mit dem Control panel, wollen wir das nacher mal im voice besprechen?

**Comment by ferb300** [comment]
GET /api/v1/liveticker => liefert JSON
POST /admin/controls/liveticker => setzt json werte
