### ISSUE TITLE
iOS push notifications kommen nicht an

### ISSUE THREAD

**Issue by craeosh** [AppFridaysForFutureDE/backend#117]
Die push notifications für neue Artikel in der App kommen immer noch nicht an.

- Neuinstallation der App ändert nichts daran
- Ich hab bei mehreren Leuten nachgefragt, die die App auch unter iOS nutzen und sie haben dasselbe Problem
- Push notifications für den Streikalarm kommen an

**Comment by ferb300** [comment]
Ist das allgemein oder unter bestimmten Umständen?

**Comment by craeosh** [comment]
Allgemein.
Also es kommen gar keine Artikel-Benachrichtigungen an. Egal welche Kategorie.

**Comment by ferb300** [comment]
ok ich schaue es mir grade an

**Comment by ferb300** [comment]
also das backend liest die post data von ghost nicht richtig ein. arbeite grade an nem fix.

**Comment by ferb300** [comment]
fix ist in fix/notifs und kann nach dem control panel gemerget werden.
Ist ja nicht zeitsensitiv (wenig artikel mit push)

**Comment by ferb300** [comment]
fix gemerget und deployt
