### ISSUE TITLE
API Dokumentation?

### ISSUE THREAD

**Issue by niansa** [AppFridaysForFutureDE/backend#130]
Hi,

ich versuche aktuell, mein eigenes Frontend zu schreiben, jedoch finde ich keine API-Dokumentation.

Btw: gibt es einen Link zu einem Diskussionskanal/-gruppe, wo ich Fragen zum Backend fragen kann?

Nils/tuxifan

**Comment by ferb300** [comment]
Hey niansa,
wir haben keine aktuelle API-Dokumentation, aber danke für die Anregung. Wir werden daran arbeiten.
Wir haben keinen Diskussionskanal für das Backend, aber du bist wilkommen, für deine Fragen hier Issues zu öffnen.

**Comment by niansa** [comment]
Alles klar. :+1:

**Comment by niansa** [comment]
Einen kurzen Rat brauch ich, in welchen Verzeichnissen befinden sich endpoints?

**Comment by ferb300** [comment]
https://github.com/AppFridaysForFutureDE/backend/blob/add_campaigns/src/express/routes.ts
Die findest du hier :)
Am besten nimmst du den branch aus meinem link, da dort alles ein bisschen klarer ist als im master :)

**Comment by Niwla23** [comment]
https://github.com/AppFridaysForFutureDE/backend/blob/master/doc/swagger.yaml
Ist das nicht die Dokumentation?

**Comment by ferb300** [comment]
die ist aber nicht up to date :)

**Comment by niansa** [comment]
> https://github.com/AppFridaysForFutureDE/backend/blob/add_campaigns/src/express/routes.ts
> Die findest du hier :)
> Am besten nimmst du den branch aus meinem link, da dort alles ein bisschen klarer ist als im master :)
@ferb300 Tja nur irgendwie ist das ein 404 Not Found
