### ISSUE TITLE
Streik endpunkt umbenennen

### ISSUE THREAD

**Issue by ferb300** [AppFridaysForFutureDE/backend#89]
und dann einen nginx redirect bis das frontend das auch hat

**Comment by NikolaiKircher** [comment]
wir könnten auch den bestehenden endpunkt so belassen und an sinnvollen stellen dokumentation bzw. kommentare erstellen mit dem hinweis, dass auch andere events wie z.B. Plenums-Termine über strikes ausgeliefert werden.

ich persönlich finde es sogar sauberer einen "inkorrekt" benannten endpoint zu haben, bevor wir da jetzt ein riesen fass auf machen mit änderungen im backend, änderungen im frontend und zusätzlichen übergangslösungen im webserver (bei denen wir nicht wissen, wie lange wir sie behalten müssen)
